#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

filepath=$1
serverIP=$2
username=$3
sshPath=$4

scp -s "$sshPath" "$filepath" "$username@$serverIP:~/"
