#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

filepath=$1
serverIP=$2
username=$3
sshPath=$4

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$filepath" "$username@$serverIP:~/"
else
	scp -s "$sshPath" "$filepath" "$username@$serverIP:~/"
fi
