#!/usr/bin/env bash
# Install nginx web server
sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
