#!/usr/bin/env bash
# Bash script to install nginx web server

apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
systemctl restart nginx
