#!/usr/bin/env bash
# Bash script to install nginx web server

apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www
touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
