#!/usr/bin/env bash
# redirects users to another page

apt-get -y update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
    listen 80 default server;
    listen [::]:80 defauls server;
    root /var/www/html
    index index.html index.htm index.ngn-debian.html
    server_name_;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}" > /etc/nginx/sites-available/default
systemctl restart nginx
