#!/usr/bin/env bash
# Bash script to install nginx web server

apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www
touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html

printf %s "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-enabled/default

service nginx restart
