#!/usr/bin/env bash
# Bash script to configure nginx 404 page

apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www
sudo chown -R "$USER:$USER" /etc/nginx
touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-enabled/default

service nginx restart
