#!/usr/bin/env bash
# Installs and configures Haproxy Load balancer

sudo apt update
sudo apt install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch sudo /etc/haproxy/haproxy.cfg

printf %s "global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 18.207.141.82:80 check
    server web-02 34.227.101.66:80 check
" > /etc/haproxy/haproxy.cfg

sudo touch /etc/init.d/haproxy

printf %s "#!/bin/sh
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    \$local_fs \$network \$syslog
# Required-Stop:     \$local_fs \$network \$syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HAProxy
# Description:       HAProxy Load Balancer
### END INIT INFO

# Author: Your Name <youremail@domain.com>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=/usr/sbin/haproxy
CONFIG=/etc/haproxy/haproxy.cfg
PIDFILE=/var/run/haproxy.pid
DESC=\"HAProxy Load Balancer\"

test -x $DAEMON || exit 0
test -f $CONFIG || exit 0

. /lib/lsb/init-functions

case \"$1\" in
  start)
    log_daemon_msg \"Starting $DESC\"
    start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON -- -f $CONFIG -D -p $PIDFILE
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg \"Stopping $DESC\"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 5
    log_end_msg $?
    ;;
  restart|force-reload)
    $0 stop && sleep 2 && $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $DESC && exit 0 || exit $?
    ;;
  *)
    echo \"Usage: /etc/init.d/haproxy {start|stop|restart|force-reload|status}\"
    exit 1
    ;;
esac

exit 0
" > /etc/init.d/haproxy

sudo chmod +x /etc/init.d/haproxy
sudo update-rc.d haproxy defaults

sudo service haproxy restart
