#!/usr/bin/env bash
# This script reconfigures nginx to listens to port 80
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
