#!/usr/bin/env bash
# Manages the manae_my_process process
com=$1
pid=$(pgrep -f manage_my_process)
if [ "$com" == 'start' ]
then
    ./manage_my_process &
    echo "$pid" > /var/run/my_process.pid
    echo "manage_my_process started"

elif [ "$com" == 'stop' ]
then
    kill "$pid"
    echo "manage_my_process stopped"
    rm /var/run/my_process.pid

elif [ "$com" == 'restart' ]
then
    kill "$pid" manage_my_process
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo "$pid" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
