#!/usr/bin/env bash
# Manages the manae_my_process process
com=$1
if [ "$com" == 'start' ]
then
    echo "manage_my_process started"
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo $! > /var/run/my_process.pid

elif [ "$com" == 'stop' ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid

elif [ "$com" == 'restart' ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm  /var/run/my_process.pid
    touch /var/run/my_process.pid
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
