#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
    # script should only display:
    # username
    # user id
    # Home directory path for the user

while IFS=: read -r username __ uid __ home
do
    echo "$username:$uid:$home"
done < /etc/passwd
