#!/usr/bin/env bash
# Prints "Best school ten times. prints "HI" in the 9th iteration
a=0
while [ $a -lt 10 ]
do
    echo "Best School"
    if [ "$a" -eq 8 ]
    then
        echo "Hi"
    fi
    ((a++))
done
