#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
    # display hours from 0 to 12
    # display minutes from 1 to 59
i=0
count=0
hour=0
while [ $count -le 779 ]
do
    if ((i != 0 & i % 60 == 0))
    then
        ((hour++))
    fi

    if ((i == 0 || i % 60 == 0))
    then
        echo "Hour: $hour"
        i=0
    else
        echo "$i"
    fi

    ((i++))
    ((count++))
done
