#!/usr/bin/env bash
# Basch script to configure ubuntu server

# copy and backup the original hosts file
cp /etc/hosts /etc/hosts.bac

# append the new configurations
127.0.0.2   localhost >> /etc/hosts
8.8.8.8     facebook.com >> /etc/hosts
