#!/usr/bin/env bash
# Basch script to configure ubuntu server

# copy and backup the original hosts file to Home directory
cp /etc/hosts ~/hosts.bac

# append the new configurations
echo "127.0.0.2	localhost" >> ~/hosts.bac
echo "8.8.8.8	facebook.com" >> ~/hosts.bac

#copy it back to the hosts file location
cp -f ~/hosts.bac /etc/hosts
