#!/usr/bin/env bash
# SSH client configuration in your answer file to make server access easier

touch ~/.ssh/config
cat << EOF > ~/.ssh/config
Host alx-server
  User ubuntu
  Hostname 18.207.141.82
  IdentityFile ~/.ssh/id_rsa
  PasswordAuthentication no
EOF
