#!/usr/bin/env bash
# SSH client configuration in your answer file to make server access easier

touch ~/.ssh/config
cat << EOF > ~/.ssh/config
Host alx-server
  User ubuntu
  Hostname 100.25.3.147
  IdentityFile ~/.ssh/school
  PasswordAuthentication no
EOF
